import { run } from "./harness.ts";

import "./classifier.test.ts";
import "./receipt-extraction.test.ts";
import "./validation.test.ts";
import "./export.test.ts";
import "./prompts.test.ts";
import "./agent-context.test.ts";
import "./recovery.test.ts";
import "./confidence-ux.test.ts";
import "./preprocess.test.ts";
import "./grounding-evidence.test.ts";
import "./entity-cleaner.test.ts";
import "./arabic-ocr.test.ts";
import "./arabic-corpus.test.ts";
import "./layout-geometry.test.ts";
import "./layout-models.test.ts";
import "./layout-spatial-index.test.ts";
import "./layout-graph.test.ts";
import "./edge-types.test.ts";
import "./region-types.test.ts";
import "./node-levels.test.ts";
import "./confidence.test.ts";
import "./semantic-graph.test.ts";
import "./layout-validation.test.ts";
import "./layout-stats.test.ts";
import "./layout-blocks.test.ts";
import "./layout-segmentation.test.ts";
import "./layout-segmentation-validation.test.ts";
import "./layout-hierarchy.test.ts";
import "./layout-hierarchy-builder.test.ts";
import "./layout-hierarchy-validation.test.ts";

await run();
